kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-server-deployment
  namespace: prod-stablecog
  labels:
    app: sc-server
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: sc-server
  template:
    metadata:
      labels:
        app: sc-server
    spec:
      containers:
        - name: sc-server
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 2Gi
          ports:
            - containerPort: 13337
          imagePullPolicy: "Always"
          startupProbe:
            httpGet:
              path: /v1/health
              port: 13337
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 13337
            initialDelaySeconds: 0
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 13337
            initialDelaySeconds: 15
            periodSeconds: 10
          env:
            - name: GOTRUE_URL
              value: http://supabase-supabase-auth.prod-supabase:9999
            - name: PUBLIC_SUPABASE_REFERENCE_ID
              value: jaqefzjqokaemzyvjcew
            - name: PRODUCTION
              value: "true"
            - name: BUCKET_BASE_URL
              value: https://b.stablecog.com
            - name: PUBLIC_API_URL
              value: https://api.stablecog.com
            - name: PRIVATE_LINGUA_API_URL
              value: http://lingua-service.prod-stablecog:13339/lingua
            - name: STRIPE_STARTER_PRODUCT_ID
              value: prod_NTzD6l0KByWfLm
            - name: STRIPE_PRO_PRODUCT_ID
              value: prod_NTzCojAHPw6tbX
            - name: STRIPE_ULTIMATE_PRODUCT_ID
              value: prod_NTzE0C8bEuIv6F
            - name: STRIPE_STARTER_PRICE_ID
              value: price_1Mj1EqATa0ehBYTAw4xFqw2s
            - name: STRIPE_PRO_PRICE_ID
              value: price_1Mj1EZATa0ehBYTAMf839xbe
            - name: STRIPE_ULTIMATE_PRICE_ID
              value: price_1Mj1FfATa0ehBYTAD3iLwSav
            - name: STRIPE_MEDIUM_PACK_PRICE_ID
              value: price_1Mj1FjATa0ehBYTACkdGOPHR
            - name: STRIPE_MEDIUM_PACK_PRODUCT_ID
              value: prod_NTzEOBmfK1DFMs
            - name: STRIPE_LARGE_PACK_PRICE_ID
              value: price_1Mj1FpATa0ehBYTATTb8FzLg
            - name: STRIPE_LARGE_PACK_PRODUCT_ID
              value: prod_NTzE9KmD5wfCYn
            - name: STRIPE_MEGA_PACK_PRICE_ID
              value: price_1Mr4aEATa0ehBYTAalXOVpeg
            - name: STRIPE_MEGA_PACK_PRODUCT_ID
              value: prod_NcJCespFpjjQJj
            - name: DISCORD_WEBHOOK_URL_DEPLOY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: DISCORD_WEBHOOK_URL_DEPLOY
            - name: MEILI_URL
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MEILI_URL
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MEILI_MASTER_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_USER
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTGRES_DB
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: STRIPE_ENDPOINT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: STRIPE_SECRET_KEY
            - name: SUPABASE_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: SUPABASE_ADMIN_KEY
            - name: REDIS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: REDIS_CONNECTION_STRING
            - name: SC_WORKER_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: SC_WORKER_WEBHOOK_SECRET
            - name: MIXPANEL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MIXPANEL_API_KEY
            - name: MIXPANEL_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: MIXPANEL_ENDPOINT
            - name: DISCORD_WEBHOOK_URL_NEWSUB
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: DISCORD_WEBHOOK_URL_NEWSUB
            - name: POSTHOG_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTHOG_API_KEY
            - name: POSTHOG_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: POSTHOG_ENDPOINT
            - name: S3_IMG2IMG_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_ACCESS_KEY
            - name: S3_IMG2IMG_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_BUCKET_NAME
            - name: S3_IMG2IMG_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_ENDPOINT
            - name: S3_IMG2IMG_REGION
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_REGION
            - name: S3_IMG2IMG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_SECRET_KEY
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_ACCESS_KEY
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_BUCKET_NAME
            - name: S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_ENDPOINT
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_IMG2IMG_REGION
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: S3_SECRET_KEY
            - name: QDRANT_URLS
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_URLS
            - name: QDRANT_URL
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_URL
            - name: QDRANT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_USERNAME
            - name: QDRANT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_PASSWORD
            - name: QDRANT_COLLECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: QDRANT_COLLECTION_NAME
            - name: CLIPAPI_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: CLIPAPI_ENDPOINT
            - name: CLIPAPI_SECRET
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: CLIPAPI_SECRET
            - name: CLIPAPI_URLS
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: CLIPAPI_URLS
            - name: TRANSLATOR_COG_URL
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: TRANSLATOR_COG_URL
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: OPENAI_API_KEY
            - name: CLIP_URL_TEMP
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: CLIP_URL_TEMP
            - name: GEOIP2_KEY
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: GEOIP2_KEY
            - name: GEOIP_WEBHOOK
              valueFrom:
                secretKeyRef:
                  name: sc-go
                  key: GEOIP_WEBHOOK
