kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-uploadapi-deployment
  namespace: qa-stablecog
  labels:
    app: sc-uploadapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-uploadapi
  template:
    metadata:
      labels:
        app: sc-uploadapi
    spec:
      containers:
        - name: sc-uploadapi
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
          command: ["/bin/sh", "-c"]
          args: ["/app/uploadapi"]
          ports:
            - containerPort: 13338
          readinessProbe:
            httpGet:
              path: /upload/health
              port: 13338
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /upload/health
              port: 13338
            initialDelaySeconds: 15
            periodSeconds: 10
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: sc-go
          env:
            - name: PORT
              value: "13338"
            - name: GOTRUE_URL
              value: http://supabase-supabase-auth.qa-supabase:9999
