kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-cron-deployment
  namespace: qa-stablecog
  labels:
    app: sc-cron
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sc-cron
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sc-cron
    spec:
      containers:
        - name: sc-cron
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 250m
              memory: 512Mi
          command: ["/bin/sh", "-c"]
          args: ["/app/cron -all -disable-auto-upscale"]
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: sc-go
          env:
            - name: GOTRUE_URL
              value: supabase-supabase-auth.qa-supabase:9999
            - name: PUBLIC_API_URL
              value: https://qa-api.stablecog.com
            - name: BUCKET_BASE_URL
              value: https://b.stablecog.com
            - name: PUBLIC_API_URL
              value: https://qa-api.stablecog.com
