kind: Deployment
apiVersion: apps/v1
metadata:
  name: sc-server-deployment
  namespace: qa-stablecog
  labels:
    app: sc-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sc-server
  template:
    metadata:
      labels:
        app: sc-server
    spec:
      containers:
        - name: sc-server
          image: replaceme
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 13337
          readinessProbe:
            httpGet:
              path: /v1/health
              port: 13337
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /v1/health
              port: 13337
            initialDelaySeconds: 15
            periodSeconds: 10
          imagePullPolicy: "Always"
          envFrom:
            - secretRef:
                name: sc-go
          env:
            - name: GOTRUE_URL
              value: http://supabase-supabase-auth.qa-supabase:9999
            - name: BUCKET_BASE_URL
              value: https://b.stablecog.com
            - name: PUBLIC_API_URL
              value: https://qa-api.stablecog.com
            - name: STRIPE_STARTER_PRODUCT_ID
              value: prod_NPuwbni7ZNkHDO
            - name: STRIPE_PRO_PRODUCT_ID
              value: prod_NPuqoCPVl1u3Qc
            - name: STRIPE_ULTIMATE_PRODUCT_ID
              value: prod_NPuyRRiAU6TPl3
            - name: STRIPE_STARTER_PRICE_ID
              value: price_1Mf56NATa0ehBYTAHkCUablG
            - name: STRIPE_PRO_PRICE_ID
              value: price_1Mf50bATa0ehBYTAPOcfnOjG
            - name: STRIPE_ULTIMATE_PRICE_ID
              value: price_1Mf591ATa0ehBYTA6ggpEEkA
            - name: STRIPE_MEDIUM_PACK_PRICE_ID
              value: price_1MfRaaATa0ehBYTAVRW3LPdR
            - name: STRIPE_MEDIUM_PACK_PRODUCT_ID
              value: prod_NQIAwnD61CSElQ
            - name: STRIPE_LARGE_PACK_PRICE_ID
              value: price_1MhHtWATa0ehBYTAeBRQMXIP
            - name: STRIPE_LARGE_PACK_PRODUCT_ID
              value: prod_NSCIDEdB7ZHb5x
            - name: STRIPE_MEGA_PACK_PRICE_ID
              value: price_1Mr4aEATa0ehBYTAalXOVpeg
            - name: STRIPE_MEGA_PACK_PRODUCT_ID
              value: prod_NcJCespFpjjQJj
